### ISSUE TITLE
We are doing the same thing!

### ISSUE THREAD

**Issue by Gussoh** [DerTomm/SerialMqttBridge#2]
Hey!

Sorry about messing up your issues database :) I couldn't find your contact details.

I made a very similar system. Perhaps we can inspire each other or help each other out.

We have a little different approach on how the systems work but we have similar goals with the system I think.

Here is the system I built:
https://github.com/Gussoh/serial-mqtt-bridge

If you would like to discuss I'm available at gustav@sohtell.se

**Comment by DerTomm** [comment]
Hi Gustav,

I know - I found your project before I pushed my version of a MQTT to Serial bridge. As I wanted to connect a MySensors serial gateway without any changes in its protocol I decided to implement a slightly different solution which can be configured to adapt both sides.

>Perhaps we can inspire each other or help each other out.
Sure - let's do this :-)

Best regards,
Thomas

**Comment by Gussoh** [comment]
Cool,

What does the MySensors serial protocol look like? Perhaps I should adapt.
I just made mine up from scratch, but I only have like 5 nodes or anything
so they are easily adaptable still.

// Gustav

**Comment by DerTomm** [comment]
You can find the MySensors protocol description here: https://www.mysensors.org/download/serial_api_20

**Comment by Gussoh** [comment]
Ok. Thanks!

Not really compatible :/ I want my nodes to know where they are and
everything.
But I guess I might be alone with liking to put more logic inside of
arduinos :)

I'm having some issues with jssc 2.8.0 (same as you). It often does not get
the start of the serial stream. The Arduino is supposed to reset when you
connect to it but it is common that I end up in the middle of a line of
data as first data comming. Have you experienced the same problem?
Otherwise I should probably copy your connection code.

My protocol is based on a handshake being sent in the first few lines of
communication so it is a little bit of an issue that it doest always start
at the beginning. I solve the problem by attempting to connect to each
serial port a couple of times, but that is not the perfect solution
ofcourse.
