### ISSUE TITLE
Loading of plugins not working with java 11

### ISSUE THREAD

**Issue by SvenMb** [DerTomm/SerialMqttBridge#8]
Hi,
when using java 11 the reflection of the the plugin classes needs a URL where it should look for the classes (even when packed in same JAR).

So I get the following error when trying to use a plugin:

`2020-02-13 15:18:25.547 WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration`

`2020-02-13 15:18:25.560 ERROR d.r.s.SerialMqttBridge - An error occured.
java.lang.Exception: Defined MQTT publish preproecessor plugin could not be found.
`

Thanks
Sven

**Comment by DerTomm** [comment]
Hi Sven,

thanks for your report. I just made the code ready for JDK 13 usage - including all relevant project dependencies.

`jssc` had to be replaced by a much more recent fork as the original project is outdated and not compatible anymore. Unfortunately there are no builds yet on Maven Central or jitpack. So I had to add this dependency to my local maven repo to build the project.

Another major change concerns the `reflections` library. The way classes are scanned had to be changed quite a bit.

Would you mind cloning the `development` branch and test if the changes solve the issue for you? The included example plugins should now be detected again when executed locally and within the packaged jar.

Regards,
Thomas

**Comment by SvenMb** [comment]
I am on Debian with JDK11... 

When I try to start maven, the following warn message comes:
`[WARNING] The POM for com.github.java-native:jssc:jar:2.9.1 is missing, no dependency information available`

also tried with OpenJDK13 and the same warn.

++++++++
It seems that this class (jssc) is not included in Maven repository. I then changed to the older org.scream3d.jssc 2.8.0 and now it builds and runs including loading of plugin class.
+++++++++

**Comment by DerTomm** [comment]
As I wrote above the updated jssc library is not available on Maven Central yet.
So if you want to compile the code yourself you have to download the dependency from [Github](https://github.com/java-native/jssc/releases/download/v2.9.1/jssc-2.9.1.jar) and import it into your local Maven repository:

```
mvn install:install-file \
   -Dfile=<path-to-file> \
   -DgroupId=com.github.java-native \
   -DartifactId=jssc \
   -Dversion=2.9.1 \
   -Dpackaging=jar \
   -DgeneratePom=true
```

And if you want to use it with JDK 11 you also have to change the `<java.version>` setting in pom.xml to 11.

**Comment by SvenMb** [comment]
Yes, you are right, I missed that you already told me about the jssc version issue.

Everything else ist working in jdk11 and jdk13 (at least as far I tested it).
